### ISSUE TITLE
Iris key diagram inaccurate

### ISSUE THREAD

**Issue by CharlieL7** [the-via/releases#10]
The key diagram for my Iris Rev. 4 has the thumb keys in the wrong order. The key diagram is rotated from how the physical keys are. See the attached image to see exactly how the keys are swapped.

![via_iris_bug1](https://user-images.githubusercontent.com/11913076/75941809-a2d49900-5e5e-11ea-8278-2dc015580c87.png)

**Comment by Wilba6582** [comment]
We discovered that the switch matrix is different for each revision, yet there is only one keyboard definition in VIA. We will need to change the firmware to have a different `PRODUCT_ID` for each revision, and correspondingly, a different keyboard definition in VIA for each revision.

**Comment by Shredivan** [comment]
I realise theres a fix pushed for this but i'm also having this issue on the Iris rev 4, the configurator thinks its the rev 3 and is swapping the order of the thumb cluster keys around, as shown above. Im using v 1.2.7.

**Comment by nooges** [comment]
@Shredivan You’ll need to flash the keyboard with the latest hex file from here: https://caniusevia.com/docs/download_firmware

**Comment by Shredivan** [comment]
Thanks @nooges!
