### ISSUE TITLE
Using ANY QMK key codes

### ISSUE THREAD

**Issue by ArseniySavin** [the-via/releases#108]
When I'm trying to set ANY key using SPECIAL -> Any. The modal window opened and I'm writing QMK keycode. In the main window sets a sequential pressed key.

It is a bug. I think when I wrote code in the modal window and pressed CONFIRM, after must set the keycode on the button.

I want to see the code and try to fix its bug myself, but I can't find where src code VIA app.

Thank you.

**Comment by wilba** [comment]
This is fixed in the next release. In the meantime, turn of "Allow remapping via keyboard" in the Settings page.
