### ISSUE TITLE
Iris keyboard: lighting blank screen

### ISSUE THREAD

**Issue by CharlieL7** [the-via/releases#11]
When switching to the lighting tab with my Iris rev. 4 keyboard, VIA goes to a blank screen with no icons.

**Comment by Wilba6582** [comment]
This happens because VIA expects the firmware to respond to lighting commands but the firmware isn't, probably due to the firmware being old (i.e. before that was added). Try downloading and installing the latest firmware from http://caniusevia.com and also using the latest VIA release.

**Comment by FrankSalmick** [comment]
I have the same problem, updated the firmware, and still can't use the lighting tab. Is there a log file somewhere that will help?

**Comment by FrankSalmick** [comment]
Nevermind, I updated the firmware incorrectly. I did it again and the lighting tab works now. Thanks for the advice.
