### ISSUE TITLE
VIA hangs on start when keyboard is connected with a USB type C 2.0 cable

### ISSUE THREAD

**Issue by jackw01** [the-via/releases#116]
On Windows 10, VIA hangs and never opens when my Novelkeys NK65 v2 is connected with a USB 2.0 cable, but works properly when the keyboard is connected with a USB 3.0 cable. The keyboard works properly with either type of cable. I tested multiple cables of each type to ensure this is not an issue with a specific cable.

**Comment by yiancar** [comment]
Hello there,
I highly suspect that has to do with the USB hub your computer is using for those USB2.0 ports.
We have had reports of other similar issues with every keyboard that uses VIA.
I suggest trying all the USB 2.0 ports on your computer. This is not something we can fix in software as simply put it some USB hubs outright refuse to transfer the data that VIA requests.

Cheers,
Yiangos

**Comment by jackw01** [comment]
Just did some more tests. 
USB 2.0 cables work:

- When connected to my computer's rear panel USB 2.0 ports
- When connected to my computer's front panel USB 3.0 ports
- When connected to a 4-port Anker USB 3.0 hub connected to any of my computer's USB ports

And don't work

- When connected to my computer's rear panel USB 3.0 ports
- When connected to the 5-port USB 3.0 hub built into my DELL U2415 monitor connected to any of my computer's USB ports
