### ISSUE TITLE
ANY key does not accept MT(MOD_RSFT,KC_SLSH)

### ISSUE THREAD

**Issue by rooski15** [the-via/releases#15]
Attempting to add MT(MOD_RSFT,KC_SLSH) to the keymap of a BIOI G60BLE. Adding this code via the ANY key does not take. Instead, when I export and inspect the .JSON, it appears the next keycode in line is added in it's place.

I am able to add MT(MOD_RSFT,KC_SLSH) to the JSON manually and import it and the keycode will work.

**Comment by McSam27** [comment]
+1

**Comment by elagil** [comment]
Your exact example works for me in VIA 1.3.0, adding it via the ANY key.

**Comment by rooski15** [comment]
@elagil - Interesting. In 1.3.1 I still encounter the same issue. Also encounter the issue adding LCA(KC) to the keymap using any key.

**Comment by Wilba6582** [comment]
`MT(MOD_RSFT,KC_SLSH)` works in VIA 1.3.1

Not every advanced keycode is available in VIA, especially all the alias for MT() and LT().
