### ISSUE TITLE
VIA cannot detect the Keychron Q1 with knob

### ISSUE THREAD

**Issue by joycillin** [the-via/releases#150]
Keyboard: Keychron Q1 knob version
Computer software: macOS Monterey v12.1

The VIA software cannot seem to detect my device despite the keyboard being connected to the computer.
The keyboard works fine.

**Comment by binjeh** [comment]
It does once you load this [json file](https://cdn.shopify.com/s/files/1/0059/0630/1017/files/Q1_knob_ANSI_VIA_keymap_V2.0.2.json.zip?v=1639470070)

**Comment by joycillin** [comment]
Thank you so much!
