### ISSUE TITLE
Support for Mouse Keys codes

### ISSUE THREAD

**Issue by sigprof** [the-via/releases#16]
If the keyboard firmware is built with `MOUSEKEY_ENABLE = yes`, it is possible to use [Mouse Keys](https://docs.qmk.fm/#/feature_mouse_keys) in the keymap. However, VIA 1.2.7 does not support these key codes even with the “Any” feature (names such as `KC_MS_UP` are not recognized), unless raw hex codes like `0xf0` are used (then the mappings work as they should, but finding those raw codes is cumbersome).

Would it be possible to add some support for these key codes?

**Comment by sigprof** [comment]
After some more testing I noticed another problem: although the raw hex codes like `0xf0` work when entered in VIA 1.2.7 through the “Any” feature, and are written out to the JSON file using the “Save Current Layout” command, trying to use “Load Saved Layout” with that JSON file leaves the corresponding keys unmapped. So apparently even raw hex codes are not supported properly.

**Comment by Wilba6582** [comment]
mouse keys keycodes added in 1.3.0

**Comment by sigprof** [comment]
Still does not work for me with `via-1.3.0-linux.AppImage` exactly the same way as in VIA 1.2.7 — neither the short form of codes (`KC_MS_U`) nor the long form (`KC_MS_UP`) are recognized, and hex codes like `0xf0` work after entering them manually, but loading them from a saved JSON does not work.

**Comment by Wilba6582** [comment]
Fixed in v1.3.1

**Comment by nanomosfet** [comment]
im finding that it doesnt work with `via-1.3.1-mac.dmg`

does this make sense

**Comment by nanomosfet** [comment]
doesnt work for dz60rgb product

**Comment by thomasmalley** [comment]
@nanomosfet same here. Running `via-1.3.1-mac.dmg` on macOS 12.3.1 on an intel mac using [Crkbd](https://github.com/foostan/crkbd)
