### ISSUE TITLE
Macros Chord Bug

### ISSUE THREAD

**Issue by kkelvin1987** [the-via/releases#19]
**Target**: Input command / chord - [hold] Left Control + Page Up

**Issue Reconstruction**

1. Program chord: {KC_LCTL,KC_PGUP} for MACRO 0
2. Assign MACRO 0 to designated key
3. Press the designated key [MACRO 0]

**Result**: Left Shift + N (in other words, the macro types "N")

**Comment by Wilba6582** [comment]
This might be due to when QMK changed the macro protocol... for a short time, the firmware was broken. Try with latest firmware from https://caniusevia.com/docs/download_firmware/

**Comment by kkelvin1987** [comment]
Hey Wilba,

Your proposed solution works!
Thank you so much for the input.

Regards,
Kelvin
