### ISSUE TITLE
The encoder icon is not round 

### ISSUE THREAD

**Issue by thompson-vii** [the-via/releases#216]
![image](https://user-images.githubusercontent.com/31672176/196337972-83794a73-ae0d-4e06-be22-b3d3923ffd67.png)

![image](https://user-images.githubusercontent.com/31672176/196337650-6d00292a-fbcf-4e3d-aa19-af12d267f48f.png)

2.0.5

**Comment by thompson-vii** [comment]
![via_encoder_knob](https://user-images.githubusercontent.com/31672176/196340460-e3cb9e09-2bb2-410a-a21d-445e4ac2191b.svg)

for reference

**Comment by olivia** [comment]
Hello @thompson-vii, thank you for filing the issue. This bug has been fixed in https://github.com/the-via/app/commit/7d55f3cdafd47988d71bccfd212d3f2cddbe4f90.
