### ISSUE TITLE
Holding down macros

### ISSUE THREAD

**Issue by jackcannon** [the-via/releases#224]
In photoshop, you can hold down Ctrl+Opt while clicking/dragging to change the brush size. There are other combos like this that require holding down a combination of keys at once.

If I map a key to SPACE, then I can press and hold it down. However if I map a key to a macro with just SPACE (or Ctrl+SPACE, Opt+SPACE, etc), then it will input them once, and want stay held down when I keep the button pressed.

Is there a workaround for this? This is vital functionality for me

**Comment by wilba** [comment]
Use the "Any" key to type in an advanced keycode that will combine a mod key with another key. This will result in the two output key codes being held down while the key is being held down. e.g. `LCTL(KC_SPC)`

See here: https://docs.qmk.fm/#/feature_advanced_keycodes
