### ISSUE TITLE
KC_LWIN, KC_RWIN keycodes detected as invalid

### ISSUE THREAD

**Issue by VICLER** [the-via/releases#227]
Hello! 
I wanted to add a macro for win screenshot: WIN+LShift+S, and I wrote:
{KC_LWIN,KC_LSFT,KC_S}
but I get an error: Whoops! Invalid keycodes detected inside {}: KC_LWIN

**Comment by VICLER** [comment]
I downloaded the VIA from official web page, and it was v1.3.1 which is old, so I thought maybe it was the reason. But on the newest version v2.0.5 I get the same error!

**Comment by wilba** [comment]
use `KC_LGUI` instead of `KC_LWIN`
