### ISSUE TITLE
Not working with Keychron K2 Pro

### ISSUE THREAD

**Issue by davidhaley** [the-via/releases#231]
I used the AppImage on EndeavourOS.

When I load the JSON keymap file (https://cdn.shopify.com/s/files/1/0059/0630/1017/files/k2_pro_us_white_v1.0.json.zip?v=1669196879), there's an error, and it remains in the Connecting state:

![image](https://user-images.githubusercontent.com/11729897/209448285-cd1caa54-3582-4f01-bccb-012290a4a195.png)
![image](https://user-images.githubusercontent.com/11729897/209448292-ac6d30dc-cf3f-4281-b06e-5462bc9ec530.png)
![image](https://user-images.githubusercontent.com/11729897/209448297-5d48be94-a0c0-45a2-a789-22f10d908a8d.png)

```
systemd-udevd[43985]: hidraw6: /etc/udev/rules.d/92-viia.rules:1 MODE 0666
systemd-udevd[43985]: hidraw6: Setting permissions /dev/hidraw6, uid=0, gid=0, mode=0666
systemd-udevd[43985]: hidraw6: Successfully created symlink '/dev/char/241:6' to '/dev/hidraw6'
```

**Comment by hogatejon** [comment]
Was seeing the same issue, but got it working by toggling on the Use V2 definitions and then uploading the JSON file!

![image](https://user-images.githubusercontent.com/69056741/209479373-694d99bb-9fc2-435d-8ca5-b8de2c8fdcdd.png)

**Comment by davidhaley** [comment]
It loads; however, the key mapping doesn't work. If I remap any key to another key, it doesn't take effect.

**Comment by wilba** [comment]
See https://github.com/the-via/app/issues/91

**Comment by davidhaley** [comment]
> Thank you, it loads now; however, the key mapping doesn't work. If I remap any key to another key, it doesn't take effect. The 'Key Tester' works, but mapping keys does not.

Replying to my previous comment for others - Keychron support kindly pointed out that I was incorrectly attempting to remap keys on Layer 0 (Mac mode) while my keyboard was in Windows mode (Layer 2). Remapping the Layer 2 keys in Via works.
