### ISSUE TITLE
Layer Mod LM() not working when using "Any" key 

### ISSUE THREAD

**Issue by Cgmandy** [the-via/releases#239]
Utilizing a LM() command in VIA, for example `LM(1, MOD_LALT)`, will not save, and will default to `LM(0,MOD_LCTL)`. Tried this on multiple boards, and issues persists on VIA versions 2.0.5, and 2.1.0. Firmware of the board was flashed with up to date versions of QMK (compiled as of 1/11/2023)

**Comment by wilba** [comment]
![](https://media.giphy.com/media/pJmnk86fXFNmrUb8LB/giphy.gif)

Fixed.
