### ISSUE TITLE
Where is Version 3?

### ISSUE THREAD

**Issue by spencerthayer** [the-via/releases#244]
[Documentation on your public site](https://caniusevia.com/docs/v3_changes)  indicates that there is a v3 of the VIA software but I cannot find a release for it anywhere. Where can I download v3 for MacOS?

**Comment by ValdisThomann** [comment]
The documentation is referring to the version of the keyboard definition, which is independent from the version of the app. The latest version of VIA supports all keyboards definition versions. Sorry for the confusion.

There are a few different versions of things that have to be coordinated under the hood of VIA. I've raised #245 to look at clarifying the way these are communicated.
