### ISSUE TITLE
Keychron Q6 + "fn+J+Z" reset does not work with the firmware from here

### ISSUE THREAD

**Issue by AndroSteph** [the-via/releases#246]
Hello,

I have had my Q6 keyboard for a few days and if I flash with the firmware from Keychron "q6_iso_knob_V1.4.bin" I can use the "reset" keys which are "fn+J+Z" (as indicated in the Keychron DOC (https://www.keychron.com/blogs/archived/how-to-factory-reset-or-flash-your-qmk-via-enabled-keychron-q6-keyboard). However, if I use the firmware here "keychron_q6_iso_encoder_via.bin", this combination of keys "fn+J+Z" no longer works, nor does it work for the "fn" key. I don't know what to do, which keys to use to do this "reset".

If I flash again with the "q6_iso_knob_V1.4.bin" the combination for reset "fn+J+Z" works 

Do you have the same problem? Or any idea how to solve it?

I flashed with the "q6_iso_knob_V1.4.bin" only for all the light effects to work ... with the original firmwar (version?) they worked only up to number 13 (approximately)

Precision, the firmware of VIA for my Keychron Q6, I downloaded it from https://www.caniusevia.com/docs/download_firmware

Thanks :-)

Sorry for my bad english :-(

**Comment by AndroSteph** [comment]
Message posted twice, sorry :-(

https://github.com/the-via/keyboards/issues/1677

**Comment by yiancar** [comment]
@lalalademaxiya1 can you take a look?
