### ISSUE TITLE
Macro won't accept KC_PMNS

### ISSUE THREAD

**Issue by semond** [the-via/releases#25]
Can't add `{KC_PMNS}` in a macro. It says:

```
Whoops! Invalid keycodes detected inside {}: KC_PMNS
```

The longer variant for that key, `KC_KP_MINUS` is also not accepted.

VIA 1.2.7, OS X 10.13.6.

**Comment by Quendi6** [comment]
Via 2.0.5, it still a problem.

**Comment by wilba** [comment]
This is a bug, this keycode should be valid in a macro.

**Comment by joaofonsecadev** [comment]
Confirm bug with versions
Via 2.0.5, Windows 11 (Version 21H2, OS Build 22000.1098)
