### ISSUE TITLE
Received invalid protocol version from device

### ISSUE THREAD

**Issue by MateuszJuszczyk** [the-via/releases#256]
Device: Waffling60 Rev C
Vid: 0x4444
Pid: 0x0008

Is there any fix?

**Comment by EdwardCoventry** [comment]
fixed for me by adding the following to rules.mk

VIA_PROTOCOL_VERSION = 10
VIA_FIRMWARE_VERSION = 2

**Comment by MateuszJuszczyk** [comment]
SOLVED: Keyboard was connected to USB hub which didnt allow to debug properly.
