### ISSUE TITLE
VIA not recognizing Zoom65 EE wireless - unable to flash with Wuque DFU programmer

### ISSUE THREAD

**Issue by bassmongrel** [the-via/releases#266]
Just built my zoom65 EE wireless. Some of the keys are not mapping correctly, however the VIA firmware does not detect my keyboard on the 'configure' tab (creepy rocking dude just staring at me). I attempted loading the json with V2 definitions (deprecated) checked but this doesn't seem to work either. I read I may need to flash my PCB, however the Wuque DFU Upgrade Programmer (found on the Meletrix website) also does not detect my keyboard. I'm out of ideas at this point, any help would be appreciated.

**VIA Version**
Have tried using the web app and desktop app 3.0.0.

**Desktop (please complete the following information):**
Windows OS using Chrome browser

**Custom json definition?**
- [x] I am loading a custom json definition using the designer tab - json obtained from Meletrix website

**Sanity checks**
- [x] I have tried connecting the keyboard directly to the computer (i.e. not using a USB hub)
- [x] I have flashed the latest firmware from https://www.caniusevia.com/docs/download_firmware

**Comment by deftclick** [comment]
I have the same issue. Even with version 2 of the firmware. https://drive.google.com/drive/folders/1WHbYSTdrYGjnTQ0d5GsmxrvviPIeAe54

I have tried to follow the instructions here. 
https://docs.google.com/document/d/1FiWiAnXCSsFjtqqpReWLJHxV8eZ7lqBj/edit
and here
https://docs.google.com/document/d/1CI4gPj5Vdi1gn-aMRJwL95F_KaUF7zNr/edit
from here
https://drive.google.com/drive/folders/1c6Z3QMv0X-zIYhUQy4eON1vNsZnHXNAI

But, no luck. After installing the driver, the DFU software still cannot find a device to flash.

**Comment by Ahnelle** [comment]
I also have the same issue. I tried all the json files, including the one on website and it still doesn't connect. It's frustrating.

**Comment by deftclick** [comment]
I was able to get my Zoom65 EE V2, built yesterday, to be recognized by VIA after using WuqueDFUupgradeProgrammer_V2.2, which I found on Meletrix Discord. And sideloading the JSON file called "Zoom 65 V2 Pre-Flashed Firmware JSON File 2" found here
https://discord.com/channels/919202175530463272/1086121281323290735/1095222664852946946

**Comment by deftclick** [comment]
I was able to get my Zoom65 EE V2, built yesterday, to be recognized by VIA
after using WuqueDFUupgradeProgrammer_V2.2, which I found on Meletrix
Discord. And sideloading the JSON file called "Zoom 65 V2 Pre-Flashed
Firmware JSON File 2" found here
https://discord.com/channels/919202175530463272/1086121281323290735/1095222664852946946

**Comment by bassmongrel** [comment]
^^^ This json worked!! Thanks so much!! Will need to remember to check discord next time

**Comment by harrisonzw** [comment]
> I was able to get my Zoom65 EE V2, built yesterday, to be recognized by VIA after using WuqueDFUupgradeProgrammer_V2.2, which I found on Meletrix Discord. And sideloading the JSON file called "Zoom 65 V2 Pre-Flashed Firmware JSON File 2" found here
> https://discord.com/channels/919202175530463272/1086121281323290735/1095222664852946946

 @bassmongrel Could you please upload the json file here? The discord link is no longer working.

**Comment by deftclick** [comment]
This link should work. Enjoy!
https://discord.com/channels/1130829449529671722/1130829599459258379

**Comment by Schgeledon** [comment]
Hello, i have the same problem with my Zoom65 V2. 
@deftclick can you tell me which discord channel this is? The link doesn't work for me, like the old one.

**Comment by deftclick** [comment]
Sorry. I made my own Discord server and posted the json file on a channel
in it.
And I probably did something wrong.
I have the correct json that will work. It's just about me sharing it
correctly.

I will look at this a little later.

**Comment by deftclick** [comment]
Here is a link to the json file that I had success with. 

https://drive.google.com/file/d/1PqfKUcFt4FrehBAaw-81YMJZY5_OGax9/view?usp=sharing

**Comment by GabrielZacarias** [comment]
> Here is a link to the json file that I had success with.
> 
> https://drive.google.com/file/d/1PqfKUcFt4FrehBAaw-81YMJZY5_OGax9/view?usp=sharing

For new builders like myself. Thank you for this. I recently purchased the Zoom65 v2 EE. The box did not come with instructions. I was really confused why the FN key was blinking green, the rgb was off, and how long it takes to charge the battery. Granted I still don't know the last topic. 

I tried to Google a user manual for the zoom65 and found the meletrix site. Their google drive gave exact directions. However, thos directions are for the original v1 zoom65. Your json file works because its made for the v2. Importing that, allowed VIA to work properly. Many thanks.

**Comment by petedonn** [comment]
I have been trying to us VIA on my new Zoom65 v2 and following the various guides on the Meletrix website and Discord.

Keyboard isn't responding or lighting up. Any ideas what that could be?

I downloaded the software to flash it, but didn't get that far because it didn't recognise my keyboard.

**Comment by GabrielZacarias** [comment]
This is Zoom65 v2 official notions doc https://jitishere.notion.site/Zoom-65-V2-Guide-and-Resources-a4346c3205964a09a6ecfc0a0a3b4873

**Comment by deftclick** [comment]
@petedonn This makes me think that perhaps the jst cables are not connected properly.  Just a guess. Good luck.

**Comment by dharlequin** [comment]
I have just assembled my Zoom 65 v2 wirelsee. It is of course not identified by VIA, so I proceeded to custom flash it.
I'm following the official guide, and WuqueDFUupgradeProgrammer is not seeing my keyboard even after installing the drivers.

Just a heads-up to anyone following the official guide. It contains v1 of all files, which seems to not work anymore. The only way I could flash mine is using v2 files [here ](https://jitishere.notion.site/Firmware-Files-13317e797bbc4a6da2b0b65b5bc3b064).

**Comment by deftclick** [comment]
The JSON file I posted works for WuqueDFUupgradeProgrammer_V2.2

Hopefully this helps. Good luck.

**Comment by juztinevans08** [comment]
@deftclick Hello I was able to download and use the DFU Programmer but I cannot download the hex file for some reason I've tried everything. Do you mind giving us a link to download the hex file please. it should be named                                                    " WQ204A1UBT2_V30_3422_KB65_RGB_VIA_SV2.0.0_20230118.hex "

**Comment by deftclick** [comment]
This is all I have...

https://drive.google.com/drive/folders/18L2ckPb9fz_DOWWIzXJ8C1Fs-LdGsNMa?usp=drive_link

**Comment by Solron30** [comment]
Hi I have a zoom65 EE, may I know if I can use the firmware version for zoom65 v2 that is posted here to be able to upgrade my firmware for v3 definitions?
