### ISSUE TITLE
Unable to configure keyboard on macOS Catalina

### ISSUE THREAD

**Issue by mpcsh** [the-via/releases#27]
Hello! I'm using macOS 10.15.4, VIA 1.2.7. My PCB is the Wilba WT-60D (came with the Mekanisk Klippe S). When I launch VIA, it just sits in the "Searching for devices..." screen. The key tester tab works just fine, however. I'm able to successfully flash firmware with QMK toolbox, and I'm able to use the board. I'm also able to use the configure tab in Windows 10, so it must be a problem with macOS of some sort.

I'm a software engineer - let me know if I can be of assistance in fixing this. Happy to lend a hand if you've got an idea of where to start, or some docs/code I could read. Otherwise just let me know if there's any more info you need about my system. Thank you!

**Comment by baldonp1** [comment]
I'm having the same issue with my TMO using the same macOS and VIA versions. Did you end up resolving this? 

I'm thinking this may have something to do with the new permissions management in Catalina. I've had other issues in some apps where they don't ask for the permissions they need. I tried manually giving VIA the permission for input monitoring, but that didn't seem to make a difference.

**Comment by mpcsh** [comment]
I ended up just configuring on my Windows box 🤷‍♂️
