### ISSUE TITLE
Add ability to map screen brightness display controls

### ISSUE THREAD

**Issue by MudkipMao** [the-via/releases#30]
Hi VIA team,

I've switched to using VIA over QMK as of late because it is so much quicker and convenient.
That being said, one thing I miss from QMK is the ability to change screen brightness for laptops.

Maybe I'm just looking in the wrong places but I cannot find any screen brightness keycodes for the life of me.

Would it be possible to add these keycodes into via? Or point me to where they are if I am totally missing them?

Thanks!

**Comment by MudkipMao** [comment]
I figured out the keycodes after digging around in QMK.

Brightness down is 0xBE
Brightness up is 0xBD

These can be mapped using the "Any" key under Special in VIA.

I do think that this should be supported by default without having to use manual keycode values.

**Comment by Wilba6582** [comment]
screen brightness keycodes added in 1.3.0
