### ISSUE TITLE
VIA is not working for NuPhy Air96 v2 

### ISSUE THREAD

**Issue by akoken** [the-via/releases#300]
**Describe the bug**
I bought a NuPhy Air96 V2 last week. I wanted to configure it using VIA but couldn't connect. I followed the steps in the official NuPhy [docs](https://nuphy.com/pages/qmk-firmwares) to upgrade QMK firmware and upgraded to [V2.1.0](https://cdn.shopify.com/s/files/1/0268/7297/1373/files/QMK_firmware_nuphy_air96_v2_ansi_v2.1.0.bin?v=1728618274) successfully. Then tried again. still doesn't work. I cannot use the keyboard efficiently without remapping keys.

**To Reproduce**
1. Attach Keyboard
2. Click Authorize
3. Pick NuPhy Air96 V2 / Connect
4. Settings (tab)
5. Show Design Tab
6. Design (tab)
7. Load [nuphy-air96-v2-via.json](https://cdn.shopify.com/s/files/1/0268/7297/1373/files/nuphy-air96-v2-via.zip?v=1701832139)
8. Configure (tab)

**Expected behavior**
Configure tab show a keyboard with mappings.

**Screenshots**
![image](https://github.com/user-attachments/assets/2a6513a2-42e1-4c5a-ba63-5bd40692cd2f)

![image](https://github.com/user-attachments/assets/cb1b2fd2-dcf8-42cb-b369-853163b31d6c)

**VIA Version**
- [x] I am using https://usevia.app/
- [x] I am using the latest release of the desktop app from https://github.com/the-via/releases/releases/latest

**Keyboard firmware VIA protocol**
Shows "Requires connected device"

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia 15.0 Apple Silicon
 - Browser: Chrome Version 129.0.6668.100 (Official Build) (arm64)

**Custom json definition?**
- [x] I am loading a custom json definition using the designer tab

**Sanity checks**
- [x] I have tried connecting the keyboard directly to the computer (i.e. not using a USB hub)
- [x] I have flashed the latest firmware from https://www.caniusevia.com/docs/download_firmware

**Additional context**
Connect button does nothing.

**Comment by ErrOzz** [comment]
I have the same issue, but only with 2.1.0 firmware version, Wenn I roll back to 2.0.2 firmware, VIA connected successfully.

**Comment by akoken** [comment]
I contacted Nuphy support and they sent me a new json file to try. I can confirm that [this](https://github.com/user-attachments/files/17465458/nuphy-air96-v2-via3.1.json) json file works for version 2.1.0. Hope this helps!

You may want to try again @ErrOzz.

**Comment by hackosx64** [comment]
Thank you so much for your solution! It worked perfectly and saved me a lot of time and frustration. I truly appreciate your effort in sharing this detailed and effective fix. You’re awesome!
