### ISSUE TITLE
Configuration not saving after disconnecting the keyboard

### ISSUE THREAD

**Issue by theodotdot** [the-via/releases#31]
Hi,

I am running the latest release for Windows and using the TMOv2 PCB.

When I configure the keyboard, it works and still works after I close the VIA software. However, when I unplug the keyboard and replug it, the configuration is back to the default one that I had when I flashed the VIA compatible firmware.

I don't have any other VIA compatible PCB for now so I can't test it with something else.

Let me know if you want me to test anything else!

Thanks

**Comment by Winni-** [comment]
Same problem on iris v4. Does not matter what half i change layout on, it will forget it in 99%.
