### ISSUE TITLE
Disable LED timeout doesn't show a value

### ISSUE THREAD

**Issue by mikecoop** [the-via/releases#4]
Would it be possible to show a number in addition to the slider for the 'Disable LEDs after timeout (mins)' setting? Right now, I can't tell how long it's actually set for.

<img width="740" alt="sshot-6" src="https://user-images.githubusercontent.com/1671683/73304078-90bf6500-41e5-11ea-8161-7135401c4b73.png">

**Comment by olivia** [comment]
Added in Fixed in [v1.2.7](https://github.com/the-via/releases/releases/tag/v1.2.7)
