### ISSUE TITLE
HHKB Firmware Missing

### ISSUE THREAD

**Issue by hofstee** [the-via/releases#40]
https://caniusevia.com/docs/supported_keyboards/ lists HHKB and HHKB JP as supported, but the firmware is nowhere in the downloads.

**Comment by Zambumon** [comment]
Both the HHKB ANSI and JP are available at [the download firmware page](https://caniusevia.com/docs/download_firmware)

<img width="362" alt="Captura de pantalla 2020-08-02 a las 9 42 54" src="https://user-images.githubusercontent.com/14968933/89118265-8dfb4080-d4a4-11ea-9691-95e918069d9d.png">

**Comment by hofstee** [comment]
Yep, I can confirm they're there now.
