### ISSUE TITLE
How do I add more layers?

### ISSUE THREAD

**Issue by wrigleyster** [the-via/releases#49]
There are layer keys MO(0) through MO(7), however I can't seem to figure out how to define layers above no 3. The number of layers seems stuck at four: {0,1,2,3}..

For reference: I'm using `the_royal/liminal` keyboard

**Comment by Wilba6582** [comment]
The number of layers is defined by the firmware. If more are needed, and there is available EEPROM space, then the person doing the QMK firmware can change this.
