### ISSUE TITLE
Installed udev rule is debian specific

### ISSUE THREAD

**Issue by kageurufu** [the-via/releases#5]
The installed udev rule uses `GROUP="plugdev"`, which is a debian-specific group

I'd like to suggest using `TAG+="uaccess"` instead of `MODE/GROUP`. 

This is even the suggested usage [from Debian](https://wiki.debian.org/USB/GadgetSetup), and works anywhere udev is supported, instead of just debian-based distributions. Adding `TAG+="udev-acl"` as well would support *old* versions of Debian/Ubuntu as well, but I don't believe anything that old (<=13.04) is still supported

**Comment by Erovia** [comment]
@olivia 
My proposed rule:
`ACTION=="add|change" KERNEL=="hidraw*", SUBSYSTEM=="hidraw", TAG+="uaccess", RUN{builtin}+="uaccess"`

This works for newly plugged-in boards, too.

**Comment by olivia** [comment]
Fixed in [v1.2.7](https://github.com/the-via/releases/releases/tag/v1.2.7)

**Comment by Erovia** [comment]
@olivia, I'd like to respectfully disagree here.
By default, the hidraw devices have `0600` permission, so only `root` can access them. The ~~fix~~ work-around in 1.2.7 modifies the permission to `0666`, granting access to *any processes* on the user's system.

While I'm sure my proposed rule can be improved upon, it works and only grants access to the user.

**Comment by olivia** [comment]
@Erovia I attempted to use the rule you provided, and it didn't work in Ubuntu, hence my modification. I am not particularly happy with with using 0666 either, but it seemed like the best of the worst options.

 If you can provide a less permissive rule as an alternative that's more portable I am happy to replace the current rule with that.

**Comment by Erovia** [comment]
@olivia Which version of Ubuntu did you try? Just to be sure, I checked the rule with:

- Ubuntu 16.04
- Ubuntu 18.04
- Manjaro
- Fedora 31
- Fedora 32 beta

It worked for my on all. 
You can reach me on Discord if you'd like to discuss this more.
