### ISSUE TITLE
Can I add custom tap and hold keys?

### ISSUE THREAD

**Issue by mostrecent** [the-via/releases#51]
Currently Via offers a few tap'n'hold keys, e.g. space and Layer 1 or so. Can I add my own tap and holds?

**Comment by Wilba6582** [comment]
You can use the "Any" key and type in `LT()` or `MT()` advanced keycodes as per QMK documentation.

**Comment by armand1m** [comment]
I'm trying to do something like `LGUI(KC_SPACE)` with the `Any` key but it does not work :/

**Comment by armand1m** [comment]
I'm trying to use `LGUI_T(KC_SPC)` but it just makes it press both together at the same time; how can I use it as a space on tap but GUI on hold?

**Comment by AckslD** [comment]
Thanks @armand1m, I also tried `LGUI(KC_SPC)` but didn't work, `MT(MOD_LGUI, KC_SPC)` did though :+1:
