### ISSUE TITLE
Dual OLEDs are borked

### ISSUE THREAD

**Issue by GreekGeorge** [the-via/releases#62]
Both OLEDs on my Corne worked with QMK, and now the master side's OLED is not working in via. Pic related:
https://cdn.discordapp.com/attachments/656193555156434945/774366224381247528/20201106_221406.jpg

**Comment by Wilba6582** [comment]
You will have to contact the person who added VIA support to Corne. We don't have the hardware to test this.

**Comment by GreekGeorge** [comment]
Ah ok thank you!
