### ISSUE TITLE
AppImage on Arch Linux doesn't detect devices

### ISSUE THREAD

**Issue by tllya** [the-via/releases#7]

**Comment by Alexandre1999** [comment]
Had the same problem, if you are under Ubuntu add your user profile to the group plugdev by doing ```sudo usermod -a -G plugdev "username"``` replacing with your username. 
If you are using other distros it might be because the udev rule isn't proper *as pointed by kageurufu* this is solved by replacing ```GROUP="plugdev"``` by ```TAG+="uaccess"``` in ```etc/udev/rules.d/92-viia.rules```.

**Comment by tllya** [comment]
Wasn't able to resolve this issue after modifying and reloading the rules. Tested on both my Arch machines.

**Comment by Alexandre1999** [comment]
Try booting the pc with the keyboard connected, mine won't detect if connected after boot

**Comment by olivia** [comment]
Can you try out the latest release @tllya? I altered the installed rule and it has improved compatibility.

**Comment by Erovia** [comment]
@tllya and @Alexandre1999  can you check the rule I proposed in #5? It should work even after boot.

**Comment by tllya** [comment]
Tested on both of my machines and it is able to detect the keyboard after the update.
