### ISSUE TITLE
QKM Lighting labels not accurate

### ISSUE THREAD

**Issue by RaunchyUndead** [the-via/releases#79]
When trying to assign QMK lighting on layout the labels are not accurate.  Example RGB toggle does not toggle the rgb on/off, but RGB Mode+ does. This is not the only thing wrong as several of the lighting labels are mixed up.

**Comment by dekruger** [comment]
I am experiencing the same thing. Currently just using a workaround based on testing which labels actually do what functions.

**Comment by MiniNinja1** [comment]
I'm having the same issue with my KBD67 Lite R1 with the KBD67 MKII RGB V2 board. I was hoping [this firmware version](https://www.reddit.com/r/KBDfans/comments/lcidi2/kbd67_lite_firmware_version/) would perhaps fix it, but it did not. This is with VIA 1.3.1.

After trial and error though, I was able to find out which RGB setting does:
- RGB Toggle →  Nothing(?)
- RGB Mode - → either RGB Mode + or RGB Mode - (cycles RGB modes/animations)
- RGB Mode + → RGB Toggle
- Hue - → Hue + (Cycles solid color from R, G, to B)
- Hue + → either RGB Mode + or RGB Mode
- Sat + → Hue - (Cycles solid color from B, G, to R)
- Sat - → Sat + (normal RGB colors)
- Bright - → Bright + 
- Bright + → Sat - (makes the color more white)
- Effect speed - → Effect speed +
- Effect speed + → Bright -
- Everything else → Nothing(?)

**Comment by MiniNinja1** [comment]
[Found a fix!](https://github.com/qmk/qmk_firmware/issues/11157) I went ahead and downloaded the [latest firmware from VIA](https://caniusevia.com/docs/download_firmware/) (as of 25 Jan 2021), flashed it on my keeb, and now VIA has the proper mapping.

**Comment by wilba** [comment]
Firmware from the VIA website should not have this problem. It was only a problem for firmware built from QMK master branch while there was a bug in the keycodes.
