### ISSUE TITLE
Left Ctrl maps to LWin and vice versa

### ISSUE THREAD

**Issue by FrancisUsher** [the-via/releases#8]
When mapping my Equinox WKL layout, I discovered that assigning a key Left Ctrl causes it to be mapped to LWin, and vice versa.

I reproduced this in several different positions to verify it wasn't a switch/pad specific issue.

Right Ctrl and Rwin do not have this problem.

This is with Release 1.2.5

Attached please find a screenshot of the configurator and the corresponding JSON output; despite the bottom left key showing LWin in both the GUI and in the JSON file, the key is mapped to Left Ctrl on the keboard.

[equinox.json.txt](https://github.com/the-via/releases/files/4269412/equinox.json.txt)

![image](https://user-images.githubusercontent.com/9691227/75592371-001fb300-5a37-11ea-903d-dd1383e2525e.png)

**Comment by Wilba6582** [comment]
Try holding down the top left key (Tab in your layout) while inserting USB cable, this will clear some state and jump to bootloader (so you could install firmware). Then unplug and plug back in so it starts up as a keyboard. See if this fixes the problem.

If it doesn't, try installing the firmware again from https://caniusevia.com/docs/download_firmware

I assume you have a production unit (not the early prototype) so use the "ai03_equinox_rev1_via.hex" firmware.

**Comment by Wilba6582** [comment]
This issue is most likely related to QMK changing its EEPROM usage and should be fixed by installing newest firmware.

**Comment by fastjames** [comment]
I recently purchased an iris rev3, and after flashing it using the latest via firmware I also encountered this problem. The workaround is pretty easy (switch the keys in the keymap) it took me awhile to figure out what was going on.
