### ISSUE TITLE
yd60mq 16 Led not working

### ISSUE THREAD

**Issue by Elicsit** [the-via/releases#80]
When I try to use my keyboard with via the screen just goes blue once it recognizes my keyboard. This is really weird because I used via to program the same keyboard about two weeks ago and the program worked fine.

**Comment by Wilba6582** [comment]
Try installing the latest firmware from here: https://caniusevia.com/docs/download_firmware/

**Comment by Elicsit** [comment]
That's where I got it from.

**Comment by Elicsit** [comment]
> Try installing the latest firmware from here: https://caniusevia.com/docs/download_firmware/

That is where I got it from.

**Comment by Wilba6582** [comment]
It was updated when I replied. Confirm that downloading and installing firmware again does not fix the problem.

**Comment by Elicsit** [comment]
Thank you it works now.
