### ISSUE TITLE
VIA and Cannonkeys Ortho48 - space key (the 2U key) always outputs space regardless of binding (even if binding is cleared)

### ISSUE THREAD

**Issue by BB-66** [the-via/releases#94]
Cannonkeys Ortho48 and VIA 1.3.1. Firmware [link](https://raw.githubusercontent.com/the-via/firmware/master/cannonkeys_ortho48_via.bin).

Layout 47 keys (2U spacebar). The space key (the 2U key) always outputs space regardless of binding (even when binding is empty).

**Comment by nblyumberg** [comment]
I submitted a PR for this on the QMK side, it looks like the matrix definition in QMK was wrong and spacebar was chained to the wrong column (3,6) instead of (3,5). Same issue in ortho60.

**Comment by BB-66** [comment]
Sorted, many thanks!
