### ISSUE TITLE
Feature Request: Added support for the LT() command

### ISSUE THREAD

**Issue by cvsickle** [the-via/releases#98]
I frequently use the LT command to use the caps lock key to switch layers when held. It would be nice if VIA could support this, but I don't see the LT command available.

**Comment by Wilba6582** [comment]
use the MT() keycode instead.

**Comment by cvsickle** [comment]
It's possible I'm missing something, but I'm also not seeing MT() in VIA. I see MO, TG, TT, OSL, and TO as well as a handful of specific hold/tap keys in the "Layers" section.

That said, even if I could find MT(), I don't think it would do what I'm after. I want to be able to hold the Caps Lock key to momentarily toggle to a different layer while it's held, but I still want to be able to tap the Caps Lock key to toggle the Caps lock.

The straight QMK keycode for what I'm trying to accomplish is LT(1,KC_CAPS) but if there are other ways to accomplish that, I'd be happy to try those out.

**Comment by Wilba6582** [comment]
my bad, didn't read properly
First, make sure you turn off Settings->Allow remapping via keyboard (there's a bug)
Click on key in the layout
Click on the "Any" keycode in Special
Type in "LT(1,KC_CAPS)"

**Comment by cvsickle** [comment]
Oh, I totally must have missed the "Any" key. Thanks for the information!
